### ISSUE TITLE
Native ARM: Could not load ~/.Xmacs/texts/scratch/

### ISSUE THREAD

**Issue by pan93412** [XmacsLabs/mogan#457] opened 2022-12-19 16:07 UTC
Mogan always throws `Could not load ~/.Xmacs/texts/scratch` when trying to open the file by double-click or dragging to the app. `File > Open` does not affect by this issue.

https://user-images.githubusercontent.com/28441561/208467863-5073e679-c2ee-4a57-bade-1174ae9d4e8c.mp4

I have researched for it for a while, and I think it is related to the entitlements about the file access ([macOS has a sandbox that prohibits the access to outside directory of the current file directory when reading from the bookmarks](https://stackoverflow.com/questions/21039975/drag-and-drop-into-sandboxed-app)). However:

1. TeXmacs can open those properly without any entitlements:
    <img width="631" alt="image" src="https://user-images.githubusercontent.com/28441561/208468262-651eecc5-3e6c-439f-84ff-7d8fa63b0a58.png">
2. Mogan does not enable Sandbox.
3. Mogan in x86_64 ([release](https://github.com/XmacsLabs/mogan/actions/runs/3724632500)) does not affect by this issue.

I am not sure how to fix it, and as it is relatively an annoying issue. Wish it can be fixed soon! :)

---

- Environment: macOS Ventura 13.1, M1
- Build: <https://github.com/XmacsLabs/mogan/issues/367#issuecomment-1357773362>

**Comment by pan93412** [comment] 2023-02-14 10:05
Reproducible in 1.1.2-rc.2 (453ca86) under macOS 13.2 (22D49)

**Comment by pan93412** [comment] 2023-04-06 15:33
Reproducible in https://github.com/XmacsLabs/mogan/releases/tag/v1.1.2-rc4

**Comment by darcy-shen** [comment] 2023-04-07 14:06
@pan93412 Are you interested in Summer of Code: http://forum.texmacs.cn/t/summer-for-code-for-xmacslabs-in-2023/1372

**Comment by pan93412** [comment] 2023-04-07 14:15
> @pan93412 Are you interested in Summer of Code: http://forum.texmacs.cn/t/summer-for-code-for-xmacslabs-in-2023/1372

I am not familiar with C++, sorry 😞

**Comment by TomCty1120** [comment] 2023-09-14 09:25
Still reproducible in v1.1.5 [https://github.com/XmacsLabs/mogan/releases/tag/v1.1.5](url) under macOS 13.5. Any updates on this issue?

**Comment by darcy-shen** [comment] 2023-09-28 16:17
should be fixed by  https://github.com/XmacsLabs/mogan/commit/a8eb5c06492a0363bc778e29ea34b4416ddb71c6

**Comment by darcy-shen** [comment] 2023-09-28 16:20
Try https://github.com/XmacsLabs/mogan/releases/tag/v1.1.6-rc3 

If it is ok, I will publish v1.1.6 before 2023/09/29 24:00 UTF+8.

**Comment by pan93412** [comment] 2023-09-28 17:13
Works in my machine. For people who wants to try the build of v1.1.6: <https://1drv.ms/u/s!AiC-9Gl0ltrahfFdmvjAIZnUFGA4oQ?e=Md3lbu>

**Closed** 2023-09-28 17:15 UTC
Labels: plat:macosx

**Comment by TomCty1120** [comment] 2023-09-28 17:22
> Try https://github.com/XmacsLabs/mogan/releases/tag/v1.1.6-rc3
> 
> If it is ok, I will publish v1.1.6 before 2023/09/29 24:00 UTC+8.

Also works for me. Thanks!
