### ISSUE TITLE
[7_2] Page not refreshing properly in beamer mode.

### ISSUE THREAD

**Issue by bimalgaudel** [XmacsLabs/mogan#1487] opened 2023-12-18 00:36 UTC
### Mogan Version

v1.2.1-rc3

### Operating System Version and Architecture

macOS Sonoma 14.2

### Describe Bug

Please see the following screen-record.

![bug](https://github.com/XmacsLabs/mogan/assets/44385776/00288dc4-90fb-4226-a096-925702f490f1)

### Expected Behavior

The screen should refresh without retaining images from previous slide.

**Comment by darcy-shen** [comment] 2023-12-18 17:51
It is caused by the Qt 6 upgrade, will be fixed soon.

**Comment by darcy-shen** [comment] 2023-12-19 08:47
> It is caused by the Qt 6 upgrade

The assertion is false. Let me bisect to find the bug.

**Comment by darcy-shen** [comment] 2023-12-19 09:02
v1.2.0-beta1 is good and v1.2.0-rc1 is bad.

**Comment by darcy-shen** [comment] 2023-12-19 09:54
This is the root cause: https://github.com/XmacsLabs/mogan/pull/1296

**Comment by darcy-shen** [comment] 2024-01-23 08:46
The fix in https://github.com/XmacsLabs/mogan/pull/1494 is not complete. Still need to improve the impl using array but not list.

**Comment by darcy-shen** [comment] 2024-01-24 10:26
Have to keep an eye on it and then reproduce it and finally fix it.

**Comment by darcy-shen** [comment] 2024-02-09 07:03
Finally fixed by https://github.com/XmacsLabs/mogan/pull/1647

**Closed** 2024-02-09 07:04 UTC
Labels: bug
